version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 7JBqY4vy4yECrnF8k7HG5pNqrHnXHkZw
      MYSQL_USER: blog
      MYSQL_DATABASE: blog
      MYSQL_PASSWORD: blog
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - blog
networks:
    blog:
        driver: bridge