// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchBlogIDHandlerFunc turns a function with the right signature into a patch blog ID handler
type PatchBlogIDHandlerFunc func(PatchBlogIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchBlogIDHandlerFunc) Handle(params PatchBlogIDParams) middleware.Responder {
	return fn(params)
}

// PatchBlogIDHandler interface for that can handle valid patch blog ID params
type PatchBlogIDHandler interface {
	Handle(PatchBlogIDParams) middleware.Responder
}

// NewPatchBlogID creates a new http.Handler for the patch blog ID operation
func NewPatchBlogID(ctx *middleware.Context, handler PatchBlogIDHandler) *PatchBlogID {
	return &PatchBlogID{Context: ctx, Handler: handler}
}

/*PatchBlogID swagger:route PATCH /blog/{id} blog patchBlogId

Updates blog post

*/
type PatchBlogID struct {
	Context *middleware.Context
	Handler PatchBlogIDHandler
}

func (o *PatchBlogID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchBlogIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
