// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Blog example app
Handling JSON null or missing values with go-swagger example app


    Schemes:
      http
    Host: localhost:3332
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
